import "../base.just"

image := "ghcr.io/tulilirockz/hydroxide:latest"
email := "tulilirockz@proton.me"

default: auth deploy

auth:
    #!/bin/sh
    if ! podman volume ls | grep "hydroxide" ; then
        podman run --rm -it -v hydroxide_data:/home/hydroxide/.config/hydroxide:Z {{ image }} auth {{ email }}
    fi
