import "../base.just"

default: create-directories secrets deploy

create-directories:
    mkdir -p "${HOME}/srv/miniflux-db"

secrets: \
    (gen-random-key "miniflux_pgdb_pass") \
    (gen-random-key "miniflux_admin_pass" "20")
