import "../base.just"

default: deploy

allow-unprivileged:
    sysctl net.ipv4.ip_unprivileged_port_start=0
    echo 'net.ipv4.ip_unprivileged_port_start=0' > /etc/sysctl.d/50-unprivileged-ports.conf
    sysctl --system

