import "../base.just"

default: create-directories deploy

create-directories:
    mkdir -p "${HOME}/srv/freshrss/data"

user:
    podman exec -it freshrss cli/create-user.php --user alice --password alice
    podman exec -it freshrss cli/access-permissions.sh
